# For colours outside the scope of colorama
def color_text(color):
    # Define ANSI escape codes for colors
    colors = {
        "black": "\033[30m"
        , "white": "\033[97m"
        , "red": "\033[31m"
        , "green": "\033[32m"
        , "blue": "\033[34m"
        , "yellow": "\033[33m"
        , "orange": "\033[38;5;208m"
        , "purple": "\033[35m"
        , "pink": "\033[38;5;198m"
        , "grey_dark": "\033[90m"
        , "grey_light": "\033[37m"
        , "RESET": "\033[0m"  # Reset to default color
    }

    # Check if the specified color is valid
    if color.lower() in colors:
        return colors[color.lower()]
    else:
        return ""  # Return an empty string if color is not recognized

def main_options_menu(): 
    print(color_text("orange") + f"Main Options Menu:" + color_text("white"))
    print(color_text("blue") + f"1. " + color_text("white") + "Singular Tests - Generic UI Stuff")
    print(color_text("blue") + f"2. " + color_text("white") + "Batch Processes")
    print(color_text("blue") + f"3. " + color_text("white") + "Overnight Processes")
    print(color_text("blue") + f"4. " + color_text("white") + "System Administration")
    print(color_text("blue") + f"5. " + color_text("white") + "Backend Processes")
    print(color_text("blue") + f"q. " + color_text("white")+ "Quit 'BugSplatter'")


def singular_test_case_options():
    print(color_text("orange") + f"Options Menu - [" + color_text("blue") + "Single - Test Cases" + color_text("orange") + "]"  + ": " + color_text("white"))
    print(color_text("blue") + f"1" + color_text("white") + ". Genric Functions Menu")
    print(color_text("blue") + f"2" + color_text("white") + ". Menu Items - Functions Menu")
    print(color_text("blue") + f"3" + color_text("white") + ". Sub Menu Items - Functions Menu (Currently not Implemented)")
    print(color_text("blue") + f"4" + color_text("white") + ". User Tiles - Functions Menu")
    print(color_text("blue") + f"5" + color_text("white") + ". Reports - Functions Menu")
    print(color_text("blue") + f"6" + color_text("white") + ". Dashboard Reports - Functions Menu")
    print(color_text("blue") + f"q" + color_text("white") + ". Quit to 'Main Menu'")

    #print(color_text("blue") + f"1" + color_text("white") + ". loginToUserAccount()")
    #print(color_text("blue") + f"2" + color_text("white") + ". loginAndLoadHomePage()")
    #print(color_text("blue") + f"3" + color_text("white") + ". checkInitialUserRole()")
    #print(color_text("blue") + f"4" + color_text("white") + ". checkHomePageloaded()")
    #print(color_text("blue") + f"5" + color_text("white") + ". homePageLoadAdminScreen()")
    #print(color_text("blue") + f"6" + color_text("white") + ". staffAdminLoadMenuOptions()")
    #print(color_text("blue") + f"7" + color_text("white") + ". staffAdminLoadEmployees()")   
    
    #print(color_text("blue") + f"8" + color_text("white") + ". startDateOverridemployee() *1 - 5yrs employment (202.5 hours) ")
    #print(color_text("blue") + f"9" + color_text("white") + ". startDateOverridemployee() *5 - 10yrs employment (217.5 hours) ")
    #print(color_text("blue") + f"10" + color_text("white") + ". startDateOverridemployee() *10+ yrs employment (247.5 hours) ")


def batch_test_case_options(): 
    print(color_text("yellow") + f"Note*" + color_text("white") + " - Ensure excel file related to the test has been added to '/excel_sheets' folder")
    print(color_text("orange") + f"Options Menu - [" + color_text("blue") + "Batch - Test Cases" + color_text("orange") + "]" + ": " + color_text("white"))
    print(color_text("blue") + f"1" + color_text("white") + ". Create Employees")
    print(color_text("blue") + f"2" + color_text("white") + ". Fetch Tiles Per User Role")
    print(color_text("blue") + f"3" + color_text("white") + ". Fetch Reports Per User Role")
    print(color_text("blue") + f"4" + color_text("white") + ". Fetch Dashboard Reports Per User Role")
    print(color_text("blue") + f"5" + color_text("white") + ". Fetch [Admin] - Main Menu Tabs")
    print(color_text("blue") + f"6" + color_text("white") + ". Fetch [Admin] - Sub Menu Tabs")
    print(color_text("blue") + f"7" + color_text("white") + ". Fetch [Admin] - Sub Sub Menu Tabs")
    print(color_text("blue") + f"8" + color_text("white") + ". Fetch [Admin] All Tabs")
    print(color_text("blue") + f"9" + color_text("white") + ". Fetch All Homepage Objects")
    print(color_text("blue") + f"?" + color_text("white") + ". Batch Process - Start Date Overrides")
    print(color_text("blue") + f"q" + color_text("white") + ". Quit to 'Main Menu'")

# Will need to include overnight processes options menu

def generic_options_menu(): 
    print(color_text("orange") + f"\nOptions Menu - [" + color_text("blue") + "Menu Items - Test Cases" + color_text("orange") + "]" + ": " + color_text("white"))
    print(color_text("blue") + f"1" + color_text("white") + ". " + color_text("white") + "Login To User Account")
    print(color_text("blue") + f"2" + color_text("white") + ". " + color_text("white") + "Load Homepage")
    print(color_text("blue") + f"3" + color_text("white") + ". " + color_text("white") + "Check Homepage objects loaded")
    print(color_text("blue") + f"4" + color_text("white") + ". " + color_text("white") + "Check Initial User Role")
    print(color_text("blue") + f"5" + color_text("white") + ". " + color_text("white") + "Check User Role And Switch")
    print(color_text("blue") + f"q" + color_text("white") + ". Quit to 'Main Menu'")
    

def menu_item_options(): 
    print(color_text("yellow") + f"Note*" + color_text("white") + " - Ensure your account is in the right usertype otherwise test will fail")
    print("      - Please comma ', ' seperate when selecting multiple options")

    print(color_text("orange") + f"\nOptions Menu - [" + color_text("blue") + "Menu Items - Test Cases" + color_text("orange") + "]" + ": " + color_text("white"))
    print(color_text("blue") + f"1" + color_text("white") + ". " + color_text("white") + "Admin")
    print(color_text("blue") + f"2" + color_text("white") + ". " + color_text("white") + "Management")
    print(color_text("blue") + f"3" + color_text("white") + ". " + color_text("white") + "Data Processing")
    print(color_text("blue") + f"4" + color_text("white") + ". " + color_text("white") + "Bank")
    print(color_text("blue") + f"5" + color_text("white") + ". " + color_text("white") + "Self Service")
    print(color_text("blue") + f"6" + color_text("white") + ". " + color_text("white") + "Reports")
    print(color_text("blue") + f"7" + color_text("white") + ". " + color_text("white") + "Reports Dashboard")
    print(color_text("blue") + f"8" + color_text("white") + ". " + color_text("white") + "About")
    print(color_text("blue") + f"q" + color_text("white") + ". Quit to 'Main Menu'")


def singular_user_tile_options(): 
    print(color_text("yellow") + f"Note*" + color_text("white") + " - Ensure excel file related to the test has been added to '/excel_sheets' folder")
    print("      - Ensure your account is in the right usertype otherwise test will fail")
    print("      - Please comma ', ' seperate when selecting multiple options")

    print(color_text("orange") + f"\nOptions Menu - [" + color_text("blue") + "User tiles - Test Cases" + color_text("orange") + "]" + ": " + color_text("white"))
    print(color_text("blue") + f"1" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"2" + color_text("white") + ". About - Date and Amp Time Tile")
    print(color_text("blue") + f"3" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"4" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"5" + color_text("white") + ". Managment - Skills Expiry Tile")
    print(color_text("blue") + f"6" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"7" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"8" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"9" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"10" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"11" + color_text("white") + ". About - About Us Tile")
    print(color_text("blue") + f"12" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"13" + color_text("white") + ". Self Service - My Availabilities Tile")
    print(color_text("blue") + f"14" + color_text("white") + ". Self Service - MyLocations Tile")
    print(color_text("blue") + f"15" + color_text("white") + ". Self Service  - My Details Tile")
    print(color_text("blue") + f"16" + color_text("white") + ". Self Service - Recent Messages Tile")
    print(color_text("blue") + f"17" + color_text("white") + ". Managment Clockings Tile")
    print(color_text("blue") + f"18" + color_text("white") + ". About - Logo Tile")
    print(color_text("blue") + f"19" + color_text("white") + ". Managment - Absence Requests Tile")
    print(color_text("blue") + f"20" + color_text("white") + ". Self Service - MyLeave Requests Tile")
    print(color_text("blue") + f"21" + color_text("white") + ". Self Service - My Rota Old Tile")
    print(color_text("blue") + f"22" + color_text("white") + ". Managment - Admin Old Tile")
    print(color_text("blue") + f"23" + color_text("white") + ". About CurrentUsers Logged In Tile")
    print(color_text("blue") + f"24" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"25" + color_text("white") + ". About - Logout Tile")
    print(color_text("blue") + f"26" + color_text("white") + ". Managment - Rota Tile")
    print(color_text("blue") + f"27" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"28" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"29" + color_text("white") + ". Managment - Rota Changes Tile")
    print(color_text("blue") + f"30" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"31" + color_text("white") + ". Self ServicePage - Travel Expenses Tile")
    print(color_text("blue") + f"32" + color_text("white") + ". Managment Page - Exceptions Report Tile")
    print(color_text("blue") + f"33" + color_text("white") + ". Reports Page - Stand by Report Tile")
    print(color_text("blue") + f"34" + color_text("white") + ". Home Page - Next Shift Tile")
    print(color_text("blue") + f"35" + color_text("white") + ". Managment - Late Staff Tile")
    print(color_text("blue") + f"36" + color_text("white") + ". Managment - Shortfalls Allocate Tile")
    print(color_text("blue") + f"37" + color_text("white") + ". Managment - Missed Check Calls Tile")
    print(color_text("blue") + f"38" + color_text("white") + ". Managment - Refresher Training Tile")
    print(color_text("blue") + f"39" + color_text("white") + ". Managment - No Response Unconfirmed Tile")
    print(color_text("blue") + f"40" + color_text("white") + ". Data Processing - Site Training Tile")
    print(color_text("blue") + f"41" + color_text("white") + ". Managment -Shortfalls Offer Tile")
    print(color_text("blue") + f"42" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"43" + color_text("white") + ". Data Processing - Standby Staff Tile")
    print(color_text("blue") + f"44" + color_text("white") + ". Data Processing - Site Emails Tile")
    print(color_text("blue") + f"45" + color_text("white") + ". Managment - Postponed Training Tile")
    print(color_text("blue") + f"46" + color_text("white") + ". Data Processing - Summary Email Tile")
    print(color_text("blue") + f"47" + color_text("white") + ". Data Processing - Reallocate Training Tile") 
    print(color_text("blue") + f"48" + color_text("white") + ". Managment - Failed Check Calls Tile")
    print(color_text("blue") + f"49" + color_text("white") + ". Data Processing - Demand Data Tile")
    print(color_text("blue") + f"50" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"51" + color_text("white") + ". Bank - Agency Quick Request Tile")
    print(color_text("blue") + f"52" + color_text("white") + ". Bank -  Agency Authorisations Tile")
    print(color_text("blue") + f"53" + color_text("white") + ". Bank -  Search Offer Tile")
    print(color_text("blue") + f"54" + color_text("white") + ". Bank - Agency Search Tile")
    print(color_text("blue") + f"55" + color_text("white") + ". Self Service - Agency Shifts Tile")
    print(color_text("blue") + f"56" + color_text("white") + ". Managment - Timesheets Tile")
    print(color_text("blue") + f"57" + color_text("white") + ". Managment - Import Rota Data Tile")
    print(color_text("blue") + f"58" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"59" + color_text("white") + ". Self Service - Change Password Tile")
    print(color_text("blue") + f"60" + color_text("white") + ". Managment - Payroll Submission Tile")
    print(color_text("blue") + f"61" + color_text("white") + ". Managment - Clockings By Person Tile")
    print(color_text("blue") + f"62" + color_text("white") + ". Managment - Data Transfer Failures Tile")
    print(color_text("blue") + f"63" + color_text("white") + ". Managment Page - Missed Tasks Tile")
    print(color_text("blue") + f"64" + color_text("white") + ". Self Service - My Work Plan Tile")
    print(color_text("blue") + f"65" + color_text("white") + ". Managment Manager Work Plan Tile")
    print(color_text("blue") + f"66" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"67" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"69" + color_text("white") + ". Managment - Unrecognized Messages Tile")
    print(color_text("blue") + f"70" + color_text("white") + ". Managment - NHSBT Import Tile")
    print(color_text("blue") + f"71" + color_text("white") + ". Self Service - Register Mobile Tile")
    print(color_text("blue") + f"72" + color_text("white") + ". Self Service - Agency Fulfill Tile")
    print(color_text("blue") + f"73" + color_text("white") + ". Management - Hub Demand Tile")
    print(color_text("blue") + f"74" + color_text("white") + ". Managment - NHSBT Quick Entry Tile")
    print(color_text("blue") + f"75" + color_text("white") + ". Managment - Agency Quick Admin Tile")
    print(color_text("blue") + f"76" + color_text("white") + ". Managment - Section Transfers Tile")
    print(color_text("blue") + f"77" + color_text("white") + ". Bank - Agency Fulfil Tile")
    print(color_text("blue") + f"78" + color_text("white") + ". Bank - Agency Search Allocate Tile")
    print(color_text("blue") + f"79" + color_text("white") + ". Data Processing - Scheduled Rotas Tile")
    print(color_text("blue") + f"80" + color_text("white") + ". Managment - Hub Status Tile")
    print(color_text("blue") + f"81" + color_text("white") + ". Managment - Hub Visibility Tile")
    print(color_text("blue") + f"82" + color_text("white") + ". Data Processing - Scheduled Job Tile")
    print(color_text("blue") + f"83" + color_text("white") + ". Managment - Staff Quick Admin Tile")
    print(color_text("blue") + f"84" + color_text("white") + ". Self Service - My Pay slip Tile")
    print(color_text("blue") + f"85" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"86" + color_text("white") + ". Managment - Shift Swap Requests Tile")
    print(color_text("blue") + f"87" + color_text("white") + ". Self Service - My Personal Details Tile")
    print(color_text("blue") + f"88" + color_text("white") + " . Self Service - My Annualised Hours Tile")
    print(color_text("blue") + f"89" + color_text("white") + ". ut.selfServicePageLoadMyAbsencesTile")
    print(color_text("blue") + f"90" + color_text("white") + ". Data Processing -PageLoadBudgetDataTile")
    print(color_text("blue") + f"91" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"92" + color_text("white") + ". Data Processing - Event Approval Tile")
    print(color_text("blue") + f"93" + color_text("white") + ". Managment - Scenarios Upload Tile")
    print(color_text("blue") + f"94" + color_text("white") + ". Managment - Generate Log Book Numbers Tile" )
    print(color_text("blue") + f"95" + color_text("white") + ". Self Service - Casual Shift Requests Tile")
    print(color_text("blue") + f"96" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"97" + color_text("white") + ". Self Service - Email Opt Out Tile")
    print(color_text("blue") + f"98" + color_text("white") + ". Managment - Training Overdue Tile")
    print(color_text("blue") + f"99" + color_text("white") + " Managment - 12 Hour Unfilled Casuals Tile")
    print(color_text("blue") + f"100" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"101" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"102" + color_text("white") + ". Bank Page Unfilled Shifts Tile")
    print(color_text("blue") + f"103" + color_text("white") + ". Managment - Work Plan Report Tile")
    print(color_text("blue") + f"104" + color_text("white") + ". Bank - Agency Hours Tile")
    print(color_text("blue") + f"105" + color_text("white") + ". Managment - Muster List Tile")
    print(color_text("blue") + f"106" + color_text("white") + ". Self Service - My Skills Expiry Tile")
    print(color_text("blue") + f"107" + color_text("white") + ". Self Service - Chat Tile")
    print(color_text("blue") + f"108" + color_text("white") + ".  Not implemented")
    print(color_text("blue") + f"109" + color_text("white") + ". Managment - Bulk Pattern Renewal Tile")
    print(color_text("blue") + f"110" + color_text("white") + ". Self Service - Login Shortcut Tile")
    print(color_text("blue") + f"111" + color_text("white") + ". Managment - Simulate Users Tile")
    print(color_text("blue") + f"112" + color_text("white") + ". Managment - Applicants Tile")
    print(color_text("blue") + f"113" + color_text("white") + ". Managment - Training Tile")
    print(color_text("blue") + f"114" + color_text("white") + ". Self Service - Document Upload Tile")
    print(color_text("blue") + f"115" + color_text("white") + ". Managment - Document Approval Tile")
    print(color_text("blue") + f"116" + color_text("white") + ". Managment - CMCall Backs Tile")
    print(color_text("blue") + f"117" + color_text("white") + ". Managment - Details Approval Tile")
    print(color_text("blue") + f"118" + color_text("white") + ". Managment - MV Lieu Tile")
    print(color_text("blue") + f"119" + color_text("white") + ". Managment - Swedish Derogation Tile")
    print(color_text("blue") + f"120" + color_text("white") + ". Managment - My CM Call Backs Tile")
    print(color_text("blue") + f"121" + color_text("white") + ". Managment - Placement Confirmations Tile")
    print(color_text("blue") + f"122" + color_text("white") + ". Managment - SE Holiday Tile")
    print(color_text("blue") + f"123" + color_text("white") + ". Self Service - MyGDPR Tile")
    print(color_text("blue") + f"124" + color_text("white") + ". About - GDPR Terms Tile")
    print(color_text("blue") + f"125" + color_text("white") + ". About - Privacy Statement Tile")
    print(color_text("blue") + f"126" + color_text("white") + ". Managment - SE Accrued Tile")
    print(color_text("blue") + f"127" + color_text("white") + ". Managment - SE Unpaid Holiday Tile")
    print(color_text("blue") + f"128" + color_text("white") + ". Self Service - My SEH oliday Managemen tTile")
    print(color_text("blue") + f"129" + color_text("white") + ". Self Service - My SE Accrual Management TileV")
    print(color_text("blue") + f"130" + color_text("white") + ". Self Service - My SE Unpaid Holiday Management Tile")
    print(color_text("blue") + f"131" + color_text("white") + ". Managment - Staff Feedback Tile")
    print(color_text("blue") + f"132" + color_text("white") + ". Data Processing - Sailing Data Upload Tile")
    print(color_text("blue") + f"133" + color_text("white") + ". Data Processing - KABA Clock List Tile")
    print(color_text("blue") + f"134" + color_text("white") + ". Managment - Lieu Mgmt Hours Tile")
    print(color_text("blue") + f"135" + color_text("white") + ". Managment - Lieu Mgmt Days Tile")
    print(color_text("blue") + f"136" + color_text("white") + ". Managment - Wage Amendments Tile")
    print(color_text("blue") + f"137" + color_text("white") + ". Data Processing - Annual Leave Plan Upload Tile")
    print(color_text("blue") + f"138" + color_text("white") + ". Bank - Feeder DataUploader Tile")
    print(color_text("blue") + f"139" + color_text("white") + ". Bank - Tou rData Uploader Tile")
    print(color_text("blue") + f"140" + color_text("white") + ". Managment - Billing Tile")
    print(color_text("blue") + f"141" + color_text("white") + ". Managment - Test Split Drop List Page Tile")
    print(color_text("blue") + f"142" + color_text("white") + ". Managment - Interchange Screens Tile")
    print(color_text("blue") + f"143" + color_text("white") + ". Managment - Support Portal Tile")
    print(color_text("blue") + f"144" + color_text("white") + ". Data Processing - Page NHSBT Session Data Import Tile")
    print(color_text("blue") + f"145" + color_text("white") + ". Managment - Rota Tile 2")
    print(color_text("blue") + f"146" + color_text("white") + ". Managment - Schedule Timesheets Tile")
    print(color_text("blue") + f"147" + color_text("white") + ". Managment - Check Single Team Calculation Tile")
    print(color_text("blue") + f"148" + color_text("white") + ".  Not implemented")
    print(color_text("blue") + f"149" + color_text("white") + ". Managment - Submit All Timesheets Tile")
    print(color_text("blue") + f"150" + color_text("white") + ". Managment - NHSBT Import Tile")
    print(color_text("blue") + f"151" + color_text("white") + ". Managment - NHSBT Quick Entry Tile")
    print(color_text("blue") + f"152" + color_text("white") +  ".  Not implemented")
    print(color_text("blue") + f"153" + color_text("white") + ". Managment - Download ESR Files Tile")
    print(color_text("blue") + f"154" + color_text("white") + ".  Not implemented")
    print(color_text("blue") + f"155" + color_text("white") + ". Data Processing - Driver Allowance Upload Tile")
    print(color_text("blue") + f"156" + color_text("white") + ".  Not implemented")
    print(color_text("blue") + f"157" + color_text("white") + ".  Not implemented")
    print(color_text("blue") + f"158" + color_text("white") + ".  Not implemented")
    print(color_text("blue") + f"159" + color_text("white") + ".  Not implemented")
    print(color_text("blue") + f"160" + color_text("white") + ". Data Processing - Annual Leave Plan Upload Tile")
    print(color_text("blue") + f"161" + color_text("white") + ". Managment - Timesheet Runs Tile")
    print(color_text("blue") + f"162" + color_text("white") + ". Data Processing - ESR Go Import Tile")
    print(color_text("blue") + f"163" + color_text("white") + ". Managment - Annual Leave Adjustments Tile")
    print(color_text("blue") + f"164" + color_text("white") + ". Managment - Days Accrual Testing Tile")
    print(color_text("blue") + f"165" + color_text("white") + ". Managment - Hours Accrual Testing Tile")
    print(color_text("blue") + f"166" + color_text("white") + ". Data Processing - ESR Export Tile")
    print(color_text("blue") + f"167" + color_text("white") + ". Self Service - Carry Forward Request Tile")
    print(color_text("blue") + f"168" + color_text("white") + ". Managment - Carry Forward Requests Tile")
    print(color_text("blue") + f"169" + color_text("white") + ". Managment - Year Annual Leave Adjustments Tile")
    print(color_text("blue") + f"170" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"171" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"172" + color_text("white") + ". Bank - HR Data Tile")
    print(color_text("blue") + f"173" + color_text("white") + ". Managment - Hols HMgmt Hours Tile")
    print(color_text("blue") + f"174" + color_text("white") + ". Managment - Hols DMgmt Days Tile")
    print(color_text("blue") + f"175" + color_text("white") + ". Managment - My Team Rota Tile")
    print(color_text("blue") + f"176" + color_text("white") + ". Self Service - Carry Forward Requests Tile")
    print(color_text("blue") + f"177" + color_text("white") + ". Managment - Carry Forward Requests Tile2")
    print(color_text("blue") + f"178" + color_text("white") + ". Managment - Holiday Management Tile")
    print(color_text("blue") + f"179" + color_text("white") + ". Self Service My Team Rota Tile")
    print(color_text("blue") + f"180" + color_text("white") + ". Managment - Timesheet Testing Tile")
    print(color_text("blue") + f"181" + color_text("white") + ". Managment - Absence Adjustments Tile")
    print(color_text("blue") + f"182" + color_text("white") + ". Managment - Bulk Absence Booking Tile")
    print(color_text("blue") + f"183" + color_text("white") + ". Dashboard Report Export Multi To PDF Tile")
    print(color_text("blue") + f"184" + color_text("white") + ". Managment - Lock Tile Test Tile")
    print(color_text("blue") + f"185" + color_text("white") + ". Managment - Bulk Schedule Timesheets Tile")
    print(color_text("blue") + f"186" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"187" + color_text("white") + ". Managment - Manager Approval Tile")
    print(color_text("blue") + f"188" + color_text("white") + ". Self Service - My Timesheets Tile")
    print(color_text("blue") + f"189" + color_text("white") + ". Self Service -My Clockings Tile")
    print(color_text("blue") + f"190" + color_text("white") + ". Managment - Details For Approval Tile")
    print(color_text("blue") + f"191" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"192" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"193" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"194" + color_text("white") + ". Managment - Mobile Rota Tile")
    print(color_text("blue") + f"195" + color_text("white") + ". About - Full Screen Tile")
    print(color_text("blue") + f"196" + color_text("white") + ". About - Exit Full Screen Tile")
    print(color_text("blue") + f"197" + color_text("white") + ". Managment - Invoice Display Test Tile")
    print(color_text("blue") + f"198" + color_text("white") + ". Managment - Invoicing Tile")
    print(color_text("blue") + f"199" + color_text("white") + ". Managment - Nextra Mobile Tile")
    print(color_text("blue") + f"200" + color_text("white") + ". Homepage - Admin Menu Item")
    print(color_text("blue") + f"201" + color_text("white") + ". Managment - Load Knowledge Hub Tile")
    print(color_text("blue") + f"202" + color_text("white") + ". Self Service My Rota Tile")
    print(color_text("blue") + f"203" + color_text("white") + ". HomePage - Absence Summary Tile")
    print(color_text("blue") + f"204" + color_text("white") + ". HomePage - Next Absence Tile")
    print(color_text("blue") + f"205" + color_text("white") + ". " + color_text("red") + "Not implemented")
    print(color_text("blue") + f"206" + color_text("white") + ". Managment - DG Rota Test Tile")
    print(color_text("blue") + f"207" + color_text("white") + ". Self Service - Take My Photo Tile")
    print(color_text("blue") + f"208" + color_text("white") + ". Managment - Move Terminate Staff Tile")
    print(color_text("blue") + f"209" + color_text("white") + ". Managment - Timesheet Approval Tile")
    print(color_text("blue") + f"210" + color_text("white") + ". Managment - Payroll Tile")
    print(color_text("blue") + f"211" + color_text("white") + ". Data Processing - Shortfalls Import Tile")
    print(color_text("blue") + f"q" + color_text("white") + ". Quit to 'Main Menu'")



def singular_report_tile_options(): 
    print(color_text("yellow") + f"Note*" + color_text("white") + " - Ensure excel file related to the test has been added to '/excel_sheets' folder")
    print("      - Ensure your account is in the right usertype otherwise test will fail")
    print("      - Please comma ', ' seperate when selecting multiple options")

    print(color_text("orange") + f"\nOptions Menu - [" + color_text("blue") + "Reports - Test Cases" + color_text("orange") + "]" + ": " + color_text("white"))
    print(color_text("blue") + f"1" + color_text("white") + ". Reports - Lane Usage Tile")
    print(color_text("blue") + f"2" + color_text("white") + ". Reports - Absence Tile")
    print(color_text("blue") + f"3" + color_text("white") + ". Reports - Register Tile")
    print(color_text("blue") + f"4" + color_text("white") + ". Reports - Skills2 Tile")
    print(color_text("blue") + f"5" + color_text("white") + ". Reports - Messages Tile")
    print(color_text("blue") + f"6" + color_text("white") + ". Reports - Payroll Tile")
    print(color_text("blue") + f"7" + color_text("white") + ". Reports - Enhancements Tile")
    print(color_text("blue") + f"8" + color_text("white") + ". Reports - Hours Report Tile")
    print(color_text("blue") + f"9" + color_text("white") + ". Reports - Absence2 Tile")
    print(color_text("blue") + f"10" + color_text("white") + ". Reports - Clocking Attendance Tile")
    print(color_text("blue") + f"11" + color_text("white") + ". Reports - Attendance Tile")
    print(color_text("blue") + f"12" + color_text("white") + ". Reports - Skills Tile")
    print(color_text("blue") + f"13" + color_text("white") + ". Reports - Shortfalls Tile")
    print(color_text("blue") + f"14" + color_text("white") + ". Reports - Contracted Hours Tile")
    print(color_text("blue") + f"15" + color_text("white") + ". Reports - Staff Shortfalls Tile")
    print(color_text("blue") + f"16" + color_text("white") + ". Reports - Staff Clockings Tile")
    print(color_text("blue") + f"17" + color_text("white") + ". Reports - Rejected Leave Tile")
    print(color_text("blue") + f"18" + color_text("white") + ". Reports - Yearly Planner Tile")
    print(color_text("blue") + f"19" + color_text("white") + ". Reports - Bradford Factor Tile")
    print(color_text("blue") + f"20" + color_text("white") + ". Reports - Hub Demand Actual Tile")
    print(color_text("blue") + f"21" + color_text("white") + ". Reports - Hub Visibility Tile")
    print(color_text("blue") + f"22" + color_text("white") + ". Reports - Section Transfers Tile")
    print(color_text("blue") + f"23" + color_text("white") + ". Reports - Agency Onsite Tile")
    print(color_text("blue") + f"24" + color_text("white") + ". Reports - Inactive Staff Tile")
    print(color_text("blue") + f"25" + color_text("white") + ". Reports - Agency Hours Tile")
    print(color_text("blue") + f"26" + color_text("white") + ". Reports - Agency Approvals Tile")
    print(color_text("blue") + f"27" + color_text("white") + ". Reports - Authorisation Requests Tile")
    print(color_text("blue") + f"28" + color_text("white") + ". Reports - Demand Quick Entry Tile")
    print(color_text("blue") + f"29" + color_text("white") + ". Reports - Neuven Data Export Tile")
    print(color_text("blue") + f"30" + color_text("white") + ". Reports - Clocking Override Buffer Tile")
    print(color_text("blue") + f"31" + color_text("white") + ". Reports - Daily Update Log Tile")
    print(color_text("blue") + f"32" + color_text("white") + ". Reports - Holiday Slots Tile")
    print(color_text("blue") + f"33" + color_text("white") + ". Reports - Viewed Rosters Tile")
    print(color_text("blue") + f"34" + color_text("white") + ". Reports - Day Roster Tile")
    print(color_text("blue") + f"35" + color_text("white") + ". Reports - Self Service Yearly Planner Tile")
    print(color_text("blue") + f"36" + color_text("white") + ". Reports - My Holiday Slots Tile")
    print(color_text("blue") + f"37" + color_text("white") + ". Reports - Crew Management Tile")
    print(color_text("blue") + f"38" + color_text("white") + ". Reports - Job List Tile")
    print(color_text("blue") + f"39" + color_text("white") + ". Reports - Accrued Absence Hours Tile")
    print(color_text("blue") + f"40" + color_text("white") + ". Reports - WTD Report Tile")
    print(color_text("blue") + f"41" + color_text("white") + ". Reports - Employee Groups Tile")
    print(color_text("blue") + f"42" + color_text("white") + ". Reports - Crew Sailing List Tile")
    print(color_text("blue") + f"43" + color_text("white") + ". Reports - Last Working Shift Tile")
    print(color_text("blue") + f"44" + color_text("white") + ". Reports - Did Not Attend Tile")
    print(color_text("blue") + f"45" + color_text("white") + ". Reports - Lieu Vs Contracted Tile")
    print(color_text("blue") + f"46" + color_text("white") + ". Reports - WTD Tile")
    print(color_text("blue") + f"47" + color_text("white") + ". Reports - Casual Holiday Accrual Tile")
    print(color_text("blue") + f"48" + color_text("white") + ". Reports - Activity Plans Tile")
    print(color_text("blue") + f"49" + color_text("white") + ". Reports - Agency Hours Summary Tile")
    print(color_text("blue") + f"50" + color_text("white") + ". Reports - WTD New Tile")
    print(color_text("blue") + f"51" + color_text("white") + ". Reports - Column Picker Test Tile")
    print(color_text("blue") + f"52" + color_text("white") + ". Reports - Self Service Activity Tile")
    print(color_text("blue") + f"53" + color_text("white") + ". Reports - Kaba Clocking Report Tile")
    print(color_text("blue") + f"54" + color_text("white") + ". Reports - Bonuses Tile")
    print(color_text("blue") + f"55" + color_text("white") + ". Reports - Deductions Tile")
    print(color_text("blue") + f"56" + color_text("white") + ". Reports - Staff Feedback Tile")
    print(color_text("blue") + f"57" + color_text("white") + ". Reports - Work Undertaken Tile")
    print(color_text("blue") + f"58" + color_text("white") + ". Reports - New Work Added Tile")
    print(color_text("blue") + f"59" + color_text("white") + ". Reports - Billable Hours Data Dump Tile")
    print(color_text("blue") + f"60" + color_text("white") + ". Reports - Drivers Feeder List Tile")
    print(color_text("blue") + f"61" + color_text("white") + ". Reports - Drivers Coach Passengers List Tile")
    print(color_text("blue") + f"62" + color_text("white") + ". Reports - Drivers Returns Departures Analysis Tile")
    print(color_text("blue") + f"63" + color_text("white") + ". Reports - Drivers Events Changes Tile")
    print(color_text("blue") + f"64" + color_text("white") + ". Reports - Employee Calculations Tile")
    print(color_text("blue") + f"65" + color_text("white") + ". Reports - Team Calculations Tile")
    print(color_text("blue") + f"66" + color_text("white") + ". Reports - Weekly Hours Tile")
    print(color_text("blue") + f"67" + color_text("white") + ". Reports - Extra Duties Tile")
    print(color_text("blue") + f"68" + color_text("white") + ". Reports - Double Sessions Tile")
    print(color_text("blue") + f"69" + color_text("white") + ". Reports - Pay Return Tile")
    print(color_text("blue") + f"70" + color_text("white") + ". Reports - My Calculations Tile")
    print(color_text("blue") + f"71" + color_text("white") + ". Reports - New Starters Tile")
    print(color_text("blue") + f"72" + color_text("white") + ". Reports - Research Dev Tile")
    print(color_text("blue") + f"73" + color_text("white") + ". Reports - Bank Staff Usage Tile")
    print(color_text("blue") + f"74" + color_text("white") + ". Reports - Bank Staff Utilisation Tile")
    print(color_text("blue") + f"75" + color_text("white") + ". Reports - Extra Sessions Reasons Tile")
    print(color_text("blue") + f"76" + color_text("white") + ". Reports - Interface Changes Tile")
    print(color_text("blue") + f"77" + color_text("white") + ". Reports - Chart Test Tile")
    print(color_text("blue") + f"78" + color_text("white") + ". Reports - Project Work Audit Tile")
    print(color_text("blue") + f"79" + color_text("white") + ". Reports - Active Completed Projects Tile")
    print(color_text("blue") + f"80" + color_text("white") + ". Reports - Billable Hours Tile")
    print(color_text("blue") + f"81" + color_text("white") + ". Reports - Billable Hours Breakdown Tile")
    print(color_text("blue") + f"82" + color_text("white") + ". Reports - Spent Time Tile")
    print(color_text("blue") + f"83" + color_text("white") + ". Reports - Accrued Days Tile")
    print(color_text("blue") + f"84" + color_text("white") + ". Reports - Prev Sessions Report Tile")
    print(color_text("blue") + f"85" + color_text("white") + ". Reports - Support Portal Category Tile")
    print(color_text("blue") + f"86" + color_text("white") + ". Reports - Billed Days Tile")
    print(color_text("blue") + f"87" + color_text("white") + ". Reports - Month View Tile")
    print(color_text("blue") + f"88" + color_text("white") + ". Reports - PO Payroll Absence Tile")
    print(color_text("blue") + f"89" + color_text("white") + ". Reports - The Liar Tile")
    print(color_text("blue") + f"90" + color_text("white") + ". Reports - Staff Sessions Outside Home Team Tile")
    print(color_text("blue") + f"91" + color_text("white") + ". Reports - Unsubmitted Sessions Tile")
    print(color_text("blue") + f"92" + color_text("white") + ". Reports - Absence Tile")
    print(color_text("blue") + f"93" + color_text("white") + ". Reports - Sickness Tile")
    print(color_text("blue") + f"94" + color_text("white") + ". Reports - Chairman Report Tile")
    print(color_text("blue") + f"95" + color_text("white") + ". Reports - Jacicntha Chart Functionality Tile")
    print(color_text("blue") + f"96" + color_text("white") + ". Reports - Stats Tile")
    print(color_text("blue") + f"97" + color_text("white") + ". Reports - MultiPost Tile")
    print(color_text("blue") + f"98" + color_text("white") + ". Reports - Weekly Hours Tile")
    print(color_text("blue") + f"99" + color_text("white") + ". Reports - Surveyor Work Breakdown Tile")
    print(color_text("blue") + f"100" + color_text("white") + ". Reports - Work Absence Approval Rejection Breakdown Tile ")
    print(color_text("blue") + f"101" + color_text("white") + ". Reports - Delegation Report Tile")
    print(color_text("blue") + f"102" + color_text("white") + ". Reports - Timesheet Changes Tile")
    print(color_text("blue") + f"103" + color_text("white") + ". Reports - Sickness Trigger Point Tile")
    print(color_text("blue") + f"104" + color_text("white") + ". Reports - Attendance Info Tile")
    print(color_text("blue") + f"105" + color_text("white") + ". Reports - Day Allocation Tile")
    print(color_text("blue") + f"106" + color_text("white") + ". Reports - Role Allocation Tile")
    print(color_text("blue") + f"q" + color_text("white") + ". Quit to 'Main Menu'")



def singular_dashboard_reports_tile_options():
    print(color_text("yellow") + f"Note*" + color_text("white") + " - Ensure excel file related to the test has been added to '/excel_sheets' folder")
    print("      - Ensure your account is in the right usertype otherwise test will fail")
    print("      - Please comma ', ' seperate when selecting multiple options")

    print(color_text("orange") + f"\nOptions Menu - [" + color_text("blue") + "Dashboard Reports - Test Cases" + color_text("orange") + "]" + ": " + color_text("white"))
    print(color_text("blue") + f"1" + color_text("white") + ". Dashboard Reports - Skills Tile ")
    print(color_text("blue") + f"2" + color_text("white") + ". Dashboard Reports - Shortfalls Tile")
    print(color_text("blue") + f"3" + color_text("white") + ". Dashboard Reports - Bank Hours Paid ile")
    print(color_text("blue") + f"4" + color_text("white") + ". Dashboard Reports - Absence Reason Breakdown Tile")
    print(color_text("blue") + f"5" + color_text("white") + ". Dashboard Reports - Sickness Paid")
    print(color_text("blue") + f"6" + color_text("white") + ". Dashboard Reports - Sesh Expected VS Sesh Planned Tile")
    print(color_text("blue") + f"7" + color_text("white") + ". Dashboard Reports - Sesh Operatedd With Sesh Shortfall Or Surplus Tile")
    print(color_text("blue") + f"8" + color_text("white") + ". Dashboard Reports - Staffing Model Tile")
    print(color_text("blue") + f"9" + color_text("white") + ". Dashboard Reports - Session Unavailablity Tile")
    print(color_text("blue") + f"10" + color_text("white") + ". Dashboard Reports - Test Absence Drop List Tile")
    print(color_text("blue") + f"11" + color_text("white") + ". Dashboard Reports - Shortfalls Report Tile")
    print(color_text("blue") + f"12" + color_text("white") + ". Dashboard Reports - Rejected Leave Tile")
    print(color_text("blue") + f"13" + color_text("white") + ". Dashboard Reports - Contracted Hours Tile")
    print(color_text("blue") + f"14" + color_text("white") + ". Dashboard Reports - Skills List")
    print(color_text("blue") + f"15" + color_text("white") + ". Dashboard Reports - Skills Summary")
    print(color_text("blue") + f"16" + color_text("white") + ". Dashboard Reports - Test Leave Period Drop List Tile")
    print(color_text("blue") + f"17" + color_text("white") + ". Dashboard Reports - Absence Tile")
    print(color_text("blue") + f"18" + color_text("white") + ". Dashboard Reports - Absence Allowance")
    print(color_text("blue") + f"19" + color_text("white") + ". Dashboard Reports - Carry Forward Requests")
    print(color_text("blue") + f"20" + color_text("white") + ". Dashboard Reports - Clocking Reports Tile")
    print(color_text("blue") + f"21" + color_text("white") + ". Dashboard Reports - Holiday Slots")
    print(color_text("blue") + f"22" + color_text("white") + ". Dashboard Reports - Sessions Planned With Shortfall Or Surplus")
    print(color_text("blue") + f"23" + color_text("white") + ". Dashboard Reports - Annual Leave Book By Day Tile")
    print(color_text("blue") + f"24" + color_text("white") + ". Dashboard Reports - Annual Leave Book Vs Allowance Tile")
    print(color_text("blue") + f"25" + color_text("white") + ". Dashboard Reports - Employee Annual Leave Allowance Vs Booked Tile")
    print(color_text("blue") + f"16" + color_text("white") + ". Dashboard Reports - Session Overrun Reasons Tile")
    print(color_text("blue") + f"q" + color_text("white") + ". Quit to 'Main Menu'")


def system_administration_options(): 
    print(color_text("orange") + f"Options Menu - [" + color_text("blue") + "System Administration" + color_text("orange") + "]"  + ": " + color_text("white"))
    print(color_text("blue") + f"1" + color_text("white") + ". Build and Release Manifests")
    print(color_text("blue") + f"2" + color_text("white") + ". Change 'Target System'")
    print(color_text("blue") + f"3" + color_text("white") + ". Update 'Username' and 'Password'")
    print(color_text("blue") + f"4" + color_text("white") + ". Database Server List - DNS/Port")
    print(color_text("blue") + f"5" + color_text("white") + ". Web Server List - DNS/PORT")
    print(color_text("blue") + f"q" + color_text("white") + ". Quit to 'Main Menu'")

def manifest_options(): 
    print(color_text("yellow") + f"Note*" + color_text("white"))
    print("      - Ensure your account is in the right usertype otherwise test will fail")
    print("      - Please comma ', ' seperate when selecting multiple options")

    print("\n" + color_text("orange") + f"Options Menu - [" + color_text("blue") + "Build and Release Manifests" + color_text("orange") + "]"  + ": " + color_text("white"))
    print(color_text("blue") + f"1" + color_text("white") +  ". rfAdmin")
    print(color_text("blue") + f"2" + color_text("white") +  ". rfCommon")
    print(color_text("blue") + f"3" + color_text("white") +  ". rfDayView")
    print(color_text("blue") + f"4" + color_text("white") +  ". rfEditors")
    print(color_text("blue") + f"5" + color_text("white") +  ". rfGlobals")
    print(color_text("blue") + f"6" + color_text("white") +  ". rfHomepage")
    print(color_text("blue") + f"7" + color_text("white") +  ". rfJavascript")
    print(color_text("blue") + f"8" + color_text("white") +  ". rfJavascript_backup")
    print(color_text("blue") + f"9" + color_text("white") +  ". rfLogin")
    print(color_text("blue") + f"10" + color_text("white") + ". rfLoginAAD")
    print(color_text("blue") + f"11" + color_text("white") + ". rfNavigationMenu")
    print(color_text("blue") + f"12" + color_text("white") + ". rfQuickEntry")
    print(color_text("blue") + f"13" + color_text("white") + ". rfReports")
    print(color_text("blue") + f"14" + color_text("white") + ". rfRoster")
    print(color_text("blue") + f"15" + color_text("white") + ". rfTableFunctions")
    print(color_text("blue") + f"16" + color_text("white") + ". RotaPerformance")
    print(color_text("blue") + f"17" + color_text("white") + ". ^ All Generic Manifests")
    print(color_text("blue") + f"18" + color_text("white") + ". Specify Manifest not in list")
    print(color_text("blue") + f"q" + color_text("white") + ". Quit to 'System Administration'")

def backend_process_options(): 
    print(color_text("orange") + f"Options Menu - [" + color_text("blue") + "Backend Processes" + color_text("orange") + "]"  + ": " + color_text("white"))
    print(color_text("blue") + f"1" + color_text("white") + ". Timesheets Runs - Expected Vs Actual")
    print(color_text("blue") + f"2" + color_text("white") + ". Create Excel Sheet - [Admin] - Expected 'Main Menu' Tabs")
    print(color_text("blue") + f"3" + color_text("white") + ". Create Excel Sheet - [Admin] - Expected 'Sub Menu' Tabs")
    print(color_text("blue") + f"4" + color_text("white") + ". Create Excel Sheets - [Admin] - Expected 'Sub Sub' Tabs [CONTACT, LOCATION, ABSENCE, SHIFT MASK]")
    print(color_text("blue") + f"5" + color_text("white") + ". Create Excel Sheets - [Admin] - All Expected Tabs [Main, Sub, Sub-Sub]")
    print(color_text("blue") + f"6" + color_text("white") + ". Check Stored Proc Exists (specific db server)")
    print(color_text("blue") + f"q" + color_text("white") + ". Quit to 'Main Menu'")